apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudmart-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: cloudmart
    environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/Moscuuu/cloudmart.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
