spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: cloudmart
    password: localdev
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  docker:
    compose:
      enabled: true
  cloud:
    gcp:
      pubsub:
        enabled: false
