apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  annotations:
    iam.gke.io/gcp-service-account: cloudmart-product-staging@project-0042e987-ac93-43ec-a4f.iam.gserviceaccount.com
