apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  labels:
    app: order-service
data:
  DATABASE_URL: "postgresql+asyncpg://cloudmart:PLACEHOLDER@CLOUD_SQL_PRIVATE_IP:5432/orderdb"
  REDIS_URL: "redis://redis:6379/0"
  PRODUCT_SERVICE_URL: "http://product-service:8080"
  GCP_PROJECT_ID: "PROJECT_ID"
  ENVIRONMENT: "dev"
  OTEL_SERVICE_NAME: "order-service"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4317"
