apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  labels:
    app: product-service
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://CLOUD_SQL_PRIVATE_IP:5432/productdb"
  SPRING_DATASOURCE_USERNAME: "cloudmart"
  OTEL_SERVICE_NAME: "product-service"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy-traces.monitoring:4317"
