apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: product-service
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=60.0 -XX:+UseG1GC -Dio.grpc.netty.shaded.io.netty.handler.ssl.noOpenSsl=true"
          resources:
            requests:
              cpu: 25m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 768Mi
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 18
            timeoutSeconds: 5
