services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: cloudmart
      POSTGRES_PASSWORD: localdev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudmart -d orderdb"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  pubsub-emulator:
    image: google/cloud-sdk:emulators
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - "8085:8085"

  order-service:
    build: .
    profiles:
      - full
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://cloudmart:localdev@postgres:5432/orderdb
      REDIS_URL: redis://redis:6379/0
      PRODUCT_SERVICE_URL: http://host.docker.internal:8080
      PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
      GCP_PROJECT_ID: local-project
      ENVIRONMENT: local
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      pubsub-emulator:
        condition: service_started

volumes:
  pgdata:
