apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/product-service
  - ../../base/order-service
  - ../../base/frontend
  - ../../base/redis

images:
  - name: product-service
    newName: us-east1-docker.pkg.dev/project-0042e987-ac93-43ec-a4f/cloudmart-docker/product-service
    newTag: latest
  - name: order-service
    newName: us-east1-docker.pkg.dev/project-0042e987-ac93-43ec-a4f/cloudmart-docker/order-service
    newTag: latest
  - name: frontend
    newName: us-east1-docker.pkg.dev/project-0042e987-ac93-43ec-a4f/cloudmart-docker/frontend
    newTag: latest

patches:
  - path: patches/product-service.yaml
  - path: patches/order-service.yaml
  - path: patches/frontend.yaml
